name: Android CI

on:
  release:
    types: [created]

jobs:
  release:
    name: Release - Android
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon

      - name: Publish to GitHub
        shell: bash
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
          ./app/release/app-release.apk ./app/release/output-metadata.json
